version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=pixsy
      - MARIADB_DATABASE=pixsy
      - MARIADB_PASSWORD=pixsy

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=pixsy
      - DB_DATABASE=pixsy
      - DB_PASSWORD=pixsy
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
